Issue/91/implement language setting
adeekshith/watomatic pull request #141
Opened 2021-03-01 03:36 UTC by spuday90

closes #91

2021-03-01 03:37 UTC, spuday90 commented
Note: Need to implement language switch logic

2021-03-01 04:43 UTC, adeekshith commented on app/src/main/java/com/parishod/watomatic/fragment/SettingsFragment.java
> +package com.parishod.watomatic.fragment;
@spuday90 We might need a separate activity for Settings.

New settings activity or new settings activity+fragment is what we need.

Or how about this:
Android Studio: `File` ➔ `New` ➔ `Activity` ➔ `Settings Activity`
And trust Android studio will recommend the best.

2021-03-01 04:52 UTC, adeekshith commented on app/src/main/java/com/parishod/watomatic/fragment/SettingsFragment.java
> +package com.parishod.watomatic.fragment;
I need to do some research to validate/refute above suggestion but this intuitively feels wrong.

Yes, the entire app can have a single activity and a hundred fragments but what my intuitive(without much reading) suggestion is:
1. Use separate activity wherever you can. Typically every screen (in general sense) can be an activity.
2. Split Activity into fragments wherever it makes sense.
3. (if anything better exists in Android architecture components, go for it)

In our case, according to rule 1, settings can be put in a separate activity so we put it in a separate activity.

2021-03-01 04:55 UTC, adeekshith requested changes
- Implement language settings functionality
- Move Settings to separate class
- Fix below bug happening when dark/light themes are switched:

<img width="298" alt="Screen Shot 2021-02-28 at 10 24 07 PM" src="https://user-images.githubusercontent.com/2568945/109453548-ff3daa80-7a17-11eb-97de-2198ac3a0e43.png">

2021-03-01 05:11 UTC, adeekshith commented on app/src/main/java/com/parishod/watomatic/fragment/SettingsFragment.java
> +        ((MainActivity)getActivity()).showHideBackButton(true);
We can also avoid these hacks if we move to separate activity if my understanding is right.

2021-03-01 05:13 UTC, adeekshith commented on app/src/main/java/com/parishod/watomatic/fragment/SettingsFragment.java
> +        ((MainActivity)getActivity()).showHideBackButton(true);
Or I should ask, what does this do? I see this in MainFragment too

2021-03-01 07:50 UTC, adeekshith commented
@spuday90 merged main to this branch so you may need to pull it first to avoid conflicts

2021-03-02 03:32 UTC, spuday90 commented
>     * Implement language settings functionality
> 
>     * Move Settings to separate class
> 
>     * Fix below bug happening when dark/light themes are switched:
> 
> 
> <img alt="Screen Shot 2021-02-28 at 10 24 07 PM" width="298" src="https://user-images.githubusercontent.com/2568945/109453548-ff3daa80-7a17-11eb-97de-2198ac3a0e43.png">

Looks like this is fixed with separate activity for settings, Verify on your device and let me know

2021-03-02 05:32 UTC, adeekshith commented
Lots of changes not just adding activity and I do not understand some of them so I might take some sweet time reviewing it 😃.

2021-03-02 05:51 UTC, adeekshith commented on app/src/main/java/com/parishod/watomatic/fragment/SettingsFragment.java
> +        Intent intent = new Intent(getActivity(), MainActivity.class);
This should restart and open Settings activity not MainActivity. Small change but may be we can file an issue and do it later too.

2021-03-02 05:53 UTC, adeekshith commented on app/src/main/java/com/parishod/watomatic/fragment/SettingsFragment.java
> +        Intent intent = new Intent(getActivity(), MainActivity.class);
But great work @spuday90 😃👌

2021-03-02 23:37 UTC, adeekshith approved these changes
Made minor changes:
- Change prefs key
- Fix "Settings" menu label

2021-03-02 23:37 UTC, merged