Feature/make service never ending
adeekshith/watomatic pull request #319
Opened 2021-06-09 03:37 UTC by spuday90

2021-06-09 03:58 UTC, adeekshith requested changes
Git conflicts

2021-06-10 05:48 UTC, adeekshith commented
Notification icon missing

<img width="294" alt="Screen Shot 2021-06-10 at 12 47 42 AM" src="https://user-images.githubusercontent.com/2568945/121471545-7e326f80-c985-11eb-8f65-adaa1a1fe055.png">

2021-06-10 06:03 UTC, adeekshith commented
- [ ] Also, not working when data is cleared (fresh install)

2021-06-10 11:51 UTC, hegocre commented
I would also add an explanation on why they should enable the notification, and maybe even have it enabled by default so that they have the app working non-stop by default.

2021-06-10 15:20 UTC, adeekshith commented
> I would also add an explanation on why they should enable the notification

+1 

```
Always-On Notification
Permanently show icon in the notification bar when Watomatic is enabled. Enable this if the app is not working properly in the background
```
But is the help text too long?

> maybe even have it enabled by default so that they have the app working non-stop by default.

Current plan is, it should be Off for everyone by default and if the app detects service is getting killed in the background, it  prompts the user to enable it.
For this PR, it is OFF for everyone. We can do service killed detection in another iteration.

Also in the future if we can get data regarding what devices or brands are having this issue, we can enable for those brands by default (For now, a few Xiaomi and OnePlus devices seem to have this issue).

2021-06-13 03:00 UTC, adeekshith commented
- [ ] Clicking on Watomatic notification when we receive WhatsApp message (not persistent notification) is also opening Watomatic app instead of Whatsapp

2021-06-13 06:35 UTC, adeekshith commented
> > But is the help text too long?
> 
> What about
> 
> ```
> Always-On notification
> Display a persistent notification to ensure Watomatic is not killed by the system
> ```
> 
> It's shorter and I think it'll do.
> 
> > For this PR, it is OFF for everyone. We can do service killed detection in another iteration.
> 
> Sounds good!

![wato-settings-319](https://user-images.githubusercontent.com/2568945/121797703-93a6d400-cbe7-11eb-94de-b31f6542b5ee.png)

2021-06-15 02:38 UTC, spuday90 commented
>     * [ ]  Also, not working when data is cleared (fresh install)

Can you confirm this again @adeekshith

2021-06-15 04:26 UTC, adeekshith commented on app/src/main/java/com/parishod/watomatic/service/KeepAliveService.java
> +        Log.e("DEBUG", "startForeground");
`Log.e` is for errors right?

2021-06-15 04:39 UTC, adeekshith approved these changes

2021-06-15 04:41 UTC, merged